# autogenerated by txs
#include:expl3
\__draw_draw_polar:enn#S
\__draw_draw_vec_polar:enn#S
\__draw_path_arc_auxi:eennNnn#S
\__draw_path_arc_auxi:enenNnn#S
\__draw_path_grid_auxi:eennnn#S
\__draw_path_grid_auxiv:eennnnnn#S
\__draw_point_interpolate_arcaxes_auxii:ennnnnnnn#S
\__draw_point_interpolate_arcaxes_auxiii:ennnnnn#S
\__draw_point_interpolate_arcaxes_auxiv:eennnnnn#S
\__draw_point_interpolate_curve_auxii:ennnnnnnn#S
\__draw_point_interpolate_curve_auxiii:ennnnn#S
\__draw_point_interpolate_curve_auxv:eew#S
\__draw_point_interpolate_curve_auxviii:eeeenn#S
\__draw_point_interpolate_distance:ennnn#S
\__draw_point_interpolate_line_aux:ennnn#S
\__draw_point_interpolate_line_aux:ennnnn#S
\__draw_point_intersect_circles_auxii:eennnnn#S
\__draw_point_intersect_circles_auxiii:eennnnn#S
\__draw_point_intersect_circles_auxiv:ennnnnnn#S
\__draw_point_intersect_circles_auxv:eennnnnnn#S
\__draw_point_intersect_circles_auxvi:ennnnnnn#S
\__draw_point_intersect_circles_auxvii:eeennnn#S
\__draw_point_intersect_line_circle_auxii:ennnnnnn#S
\__draw_point_intersect_line_circle_auxiii:eeennnnn#S
\__draw_point_intersect_line_circle_auxiv:eennnnnn#S
\__draw_point_intersect_line_circle_auxv:ennnn#S
\__draw_point_intersect_lines_aux:eeeeee#S
\__draw_point_process_auxi:en#S
\__draw_point_process_auxiii:een#S
\__draw_point_process_auxv:eeen#S
\__draw_point_process_auxvii:eeeen#S
\__draw_point_to_dim:e#S
\__draw_point_unit_vector:enn#S
\__draw_point_vec:ee#S
\__draw_point_vec:eee#S
\__draw_quark_recursion_tail:w#S
\__draw_softpath_add:e#S
\__draw_softpath_add:o#S
\__draw_softpath_round_calc:eVnnnn#S
\__draw_softpath_roundpoint:VV#S
\__draw_transform_invert:e#S
\__draw_transform_rotate:e#S
\__draw_transform_rotate:ee#S
\__draw_use_i_delimit_by_q_recursion_stop:nw#S
\__file_name=expl3.sty#S
\__file_seen_expl3.sty:#S
\__hook expl3#S
\__hook package/expl3/after#S
\__hook package/expl3/before#S
\__hook_next package/expl3/after#S
\__hook_next package/expl3/before#S
\c__draw_path_arc_60_fp#S
\c__draw_path_arc_90_fp#S
\exp_args:NeV#S
\exp_args:Neeee#S
\exp_args:Neeeeee#S
\exp_args:Nene#S
\g__hook_package/expl3/after_reversed_tl#S
\g__hook_package/expl3/before_reversed_tl#S
\msg extra text > draw/invalid-path-action#S
\msg extra text > draw/main-layer#S
\msg extra text > draw/main-reserved#S
\msg extra text > draw/unknown-layer#S
\msg text > draw/invalid-path-action#S
\msg text > draw/main-layer#S
\msg text > draw/main-reserved#S
\msg text > draw/unknown-layer#S
\unprocessedoptions-expl3.sty#S
csnameendcsname#S
expl3.sty#S
